GXHAssessment.Web/Models/ErrorViewModel.cs
namespace GXHAssessment.Web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

GXHAssessment.Web/Models/HealthCareProviderResultModel.cs
namespace GXHAssessment.Web.Models;

//TODO: Change the name of the properties
//https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/how-to?pivots=dotnet-7-0#deserialize-from-utf-8
public class HealthCareProviderResultModel
{
    public int result_count { get; set; }
    public List<Result>? results { get; set; }
}

public class Result
{
    public string? created_epoch { get; set; }
    public string? enumeration_type { get; set; }
    public string? last_updated_epoch { get; set; }
    public string? number { get; set; }
    public List<Address>? addresses { get; set; }
    public List<object>? practiceLocations { get; set; }
    public Basic? basic { get; set; }
    public List<Taxonomy>? taxonomies { get; set; }
    public List<Identifier>? identifiers { get; set; }
    public List<object>? endpoints { get; set; }
    public List<object>? other_names { get; set; }
}

public class Address
{
    public string? country_code { get; set; }
    public string? country_name { get; set; }
    public string? address_purpose { get; set; }
    public string? address_type { get; set; }
    public string? address_1 { get; set; }
    public string? address_2 { get; set; }
    public string? city { get; set; }
    public string? state { get; set; }
    public string? postal_code { get; set; }
    public string? telephone_number { get; set; }
    public string? fax_number { get; set; }
}

public class Basic
{
    public string? first_name { get; set; }
    public string? last_name { get; set; }
    public string? middle_name { get; set; }
    public string? credential { get; set; }
    public string? sole_proprietor { get; set; }
    public string? gender { get; set; }
    public string? enumeration_date { get; set; }
    public string? last_updated { get; set; }
    public string? status { get; set; }
    public string? name_prefix { get; set; }
    public string? name_suffix { get; set; }
    public string? certification_date { get; set; }
}

public class Identifier
{
    public string? code { get; set; }
    public string? desc { get; set; }
    public object? issuer { get; set; }
    public string? identifier { get; set; }
    public string? state { get; set; }
}

public class Taxonomy
{
    public string? code { get; set; }
    public string? taxonomy_group { get; set; }
    public string? desc { get; set; }
    public string? state { get; set; }
    public string? license { get; set; }
    public bool primary { get; set; }
}

GXHAssessment.Web/Models/WeatherForecastModel.cs
namespace GXHAssessment.Web.Models
{
    public class WeatherForecastModel
    {
        public DateTime Date { get; set; }
        public int TemperatureC { get; set; }
        public int TemperatureF { get; set; }
        public string? Summary { get; set; }
    }
}

GXHAssessment.Web/Controllers/HealthCareProvidersController.cs
using Microsoft.AspNetCore.Mvc;
using GXHAssessment.Web.Services.Interfaces;

namespace GXHAssessment.Web.Controllers;

public class HealthCareProvidersController : Controller
{
    private readonly IHealthCareProviderService _service;

    public HealthCareProvidersController(IHealthCareProviderService service)
    {
        _service = service ?? throw new ArgumentNullException(nameof(service));
    }

    public async Task<IActionResult> HealthCareProvidersIndex()
    {
        var healthCareProviders = await _service.Find();
        return View(healthCareProviders);
    }
}

GXHAssessment.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using GXHAssessment.Web.Models;

namespace GXHAssessment.Web.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

GXHAssessment.Web/Controllers/WeatherForecastController.cs
using Microsoft.AspNetCore.Mvc;
using GXHAssessment.Web.Services.Interfaces;

namespace GXHAssessment.Web.Controllers;

public class WeatherForecastController : Controller
{
    private readonly IWeatherForecastService _service;

    public WeatherForecastController(IWeatherForecastService service)
    {
        _service = service ?? throw new ArgumentNullException(nameof(service));
    }

    public async Task<IActionResult> WeatherForecastIndex()
    {
        var products = await _service.Find();
        return View(products);
    }
}

GXHAssessment.Web/Views/HealthCareProviders/HealthCareProvidersIndex.cshtml
@model GXHAssessment.Web.Models.HealthCareProviderResultModel

<br />
<br />
<table class="table">
    <tdead>
        <tr>
            <th>NPI</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Credential</th>
            <th>Status</th>
        </tr>
    </tdead>
    <tbody>
        @foreach (var healthCareProvider in Model.results)
        {
            <tr>
                <td>@healthCareProvider.number</td>
                <td>@healthCareProvider?.basic?.first_name</td>
                <td>@healthCareProvider?.basic?.last_name</td>
                <td>@healthCareProvider?.basic?.credential</td>
                <td>@healthCareProvider?.basic?.status</td>
            </tr>
        }
    </tbody>
</table>
</div>

GXHAssessment.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS
        and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in
            Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your
            applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

GXHAssessment.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>GXH Assessment - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GXHAssessment.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GXH Assessment</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WeatherForecast" asp-action="WeatherForecastIndex">Weather Forecast</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HealthCareProviders" asp-action="HealthCareProvidersIndex">Health Care Providers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GXH Assessment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GXHAssessment.Web/Views/WeatherForecast/WeatherForecastIndex.cshtml
@model IEnumerable<GXHAssessment.Web.Models.WeatherForecastModel>

<br />
<br />
<table class="table">
    <tdead>
        <tr>
            <th>Date</th>
            <th>Temperature C</th>
            <th>Temperature F</th>
            <th>Summary</th>
        </tr>
    </tdead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Date</td>
                <td>@item.TemperatureC</td>
                <td>@item.TemperatureF</td>
                <td>@item.Summary</td>
            </tr>
        }
    </tbody>
</table>
</div>